In [1]:
import pandas as pd
L1Arabic_df = pd.read_excel("/Users/samanthacreel/Documents/Dissertation/L1Arabic_Appendix.xlsx")
ZArabic_df = pd.read_excel("/Users/samanthacreel/Documents/Dissertation/ZArabic_Appendix.xlsx")

In [4]:
L1Arabic_df

,Unnamed: 0,VPC,IPA,English,Raw Freq,Norm Freq
0,1,قام ب,qa:ma bi-,carry out/undertake,54,34.17
1,2,أدى إلى,ʔadda: ʔila:,lead to,26,16.45
2,3,حصل على,ħasˤala ʕala:,obtain,24,15.19
3,4,وصل إلى,wasˤala ʔila:,reach,19,12.02
4,5,عمل على,ʕamala ʕala:,work on,18,11.39
...,...,...,...,...,...,...
267,268,نشأ من,naʃaʔa min,grow from,1,0.63
268,269,نظر في,naðˤara fi:,consider,1,0.63
269,270,نفر عن,nafara ʕan,be averse to,1,0.63
270,271,هام ب,ha:ma bi-,fall in love,1,0.63
271,272,واظب على,wa:ðˤaba ʕala:,continue with,1,0.63

In [11]:
df_2 = pd.merge(L1Arabic_df, ZArabic_df, on=["VPC"], how='right')

In [12]:
df_2

,Unnamed: 0_x,VPC,IPA_x,English_x,Raw Freq_x,Norm Freq_x,Unnamed: 0_y,IPA_y,English_y,Raw Freq_y,Norm Freq_y
0,1.0,قام ب,qa:ma bi-,carry out/undertake,54.0,34.17,5,NaN,NaN,20,30.50
1,2.0,أدى إلى,ʔadda: ʔila:,lead to,26.0,16.45,2,NaN,NaN,57,86.93
2,3.0,حصل على,ħasˤala ʕala:,obtain,24.0,15.19,11,NaN,NaN,6,9.15
3,4.0,وصل إلى,wasˤala ʔila:,reach,19.0,12.02,15,NaN,NaN,5,7.63
4,5.0,عمل على,ʕamala ʕala:,work on,18.0,11.39,12,NaN,NaN,6,9.15
...,...,...,...,...,...,...,...,...,...,...,...
67,257.0,فكر في,fakkara fi:,think about,1.0,0.63,68,NaN,NaN,1,1.53
68,262.0,لاق ب,la:qa bi-,befit,1.0,0.63,69,NaN,NaN,1,1.53
69,265.0,نتج عن,nataʒa ʕan,result from,1.0,0.63,40,NaN,NaN,2,3.05
70,NaN,سبب في,NaN,NaN,NaN,NaN,23,NaN,NaN,4,6.10
71,NaN,أخذ ب,NaN,NaN,NaN,NaN,41,NaN,NaN,1,1.53

In [14]:
df_2.to_excel("/Users/samanthacreel/Documents/Dissertation/ZArabic_Appendix_Filled.xlsx")